// This file is a preprocessor function, parameterized by the KIELI_X_BUILTIN_DO macro. It is
// invoked by including it between a define/undef pair. There are no include guards, because this
// file does not declare anything, and may be included multiple times in a translation unit.

// https://en.wikipedia.org/wiki/X_macro

// clang-format off

// Fields: identifier, spelling

KIELI_X_BUILTIN_DO(AddI8,       "addI8")
KIELI_X_BUILTIN_DO(AddI16,      "addI16")
KIELI_X_BUILTIN_DO(AddI32,      "addI32")
KIELI_X_BUILTIN_DO(AddI64,      "addI64")
KIELI_X_BUILTIN_DO(AddU8,       "addU8")
KIELI_X_BUILTIN_DO(AddU16,      "addU16")
KIELI_X_BUILTIN_DO(AddU32,      "addU32")
KIELI_X_BUILTIN_DO(AddU64,      "addU64")
KIELI_X_BUILTIN_DO(AddF32,      "addF32")
KIELI_X_BUILTIN_DO(AddF64,      "addF64")
KIELI_X_BUILTIN_DO(SubI8,       "subI8")
KIELI_X_BUILTIN_DO(SubI16,      "subI16")
KIELI_X_BUILTIN_DO(SubI32,      "subI32")
KIELI_X_BUILTIN_DO(SubI64,      "subI64")
KIELI_X_BUILTIN_DO(SubU8,       "subU8")
KIELI_X_BUILTIN_DO(SubU16,      "subU16")
KIELI_X_BUILTIN_DO(SubU32,      "subU32")
KIELI_X_BUILTIN_DO(SubU64,      "subU64")
KIELI_X_BUILTIN_DO(SubF32,      "subF32")
KIELI_X_BUILTIN_DO(SubF64,      "subF64")
KIELI_X_BUILTIN_DO(MulI8,       "mulI8")
KIELI_X_BUILTIN_DO(MulI16,      "mulI16")
KIELI_X_BUILTIN_DO(MulI32,      "mulI32")
KIELI_X_BUILTIN_DO(MulI64,      "mulI64")
KIELI_X_BUILTIN_DO(MulU8,       "mulU8")
KIELI_X_BUILTIN_DO(MulU16,      "mulU16")
KIELI_X_BUILTIN_DO(MulU32,      "mulU32")
KIELI_X_BUILTIN_DO(MulU64,      "mulU64")
KIELI_X_BUILTIN_DO(MulF32,      "mulF32")
KIELI_X_BUILTIN_DO(MulF64,      "mulF64")
KIELI_X_BUILTIN_DO(DivI8,       "divI8")
KIELI_X_BUILTIN_DO(DivI16,      "divI16")
KIELI_X_BUILTIN_DO(DivI32,      "divI32")
KIELI_X_BUILTIN_DO(DivI64,      "divI64")
KIELI_X_BUILTIN_DO(DivU8,       "divU8")
KIELI_X_BUILTIN_DO(DivU16,      "divU16")
KIELI_X_BUILTIN_DO(DivU32,      "divU32")
KIELI_X_BUILTIN_DO(DivU64,      "divU64")
KIELI_X_BUILTIN_DO(DivF32,      "divF32")
KIELI_X_BUILTIN_DO(DivF64,      "divF64")
KIELI_X_BUILTIN_DO(ModI8,       "modI8")
KIELI_X_BUILTIN_DO(ModI16,      "modI16")
KIELI_X_BUILTIN_DO(ModI32,      "modI32")
KIELI_X_BUILTIN_DO(ModI64,      "modI64")
KIELI_X_BUILTIN_DO(ModU8,       "modU8")
KIELI_X_BUILTIN_DO(ModU16,      "modU16")
KIELI_X_BUILTIN_DO(ModU32,      "modU32")
KIELI_X_BUILTIN_DO(ModU64,      "modU64")
KIELI_X_BUILTIN_DO(ModF32,      "modF32")
KIELI_X_BUILTIN_DO(ModF64,      "modF64")
KIELI_X_BUILTIN_DO(EqI8,        "eqI8")
KIELI_X_BUILTIN_DO(EqI16,       "eqI16")
KIELI_X_BUILTIN_DO(EqI32,       "eqI32")
KIELI_X_BUILTIN_DO(EqI64,       "eqI64")
KIELI_X_BUILTIN_DO(EqU8,        "eqU8")
KIELI_X_BUILTIN_DO(EqU16,       "eqU16")
KIELI_X_BUILTIN_DO(EqU32,       "eqU32")
KIELI_X_BUILTIN_DO(EqU64,       "eqU64")
KIELI_X_BUILTIN_DO(EqF32,       "eqF32")
KIELI_X_BUILTIN_DO(EqF64,       "eqF64")
KIELI_X_BUILTIN_DO(EqBool,      "eqBool")
KIELI_X_BUILTIN_DO(EqChar,      "eqChar")
KIELI_X_BUILTIN_DO(LtI8,        "ltI8")
KIELI_X_BUILTIN_DO(LtI16,       "ltI16")
KIELI_X_BUILTIN_DO(LtI32,       "ltI32")
KIELI_X_BUILTIN_DO(LtI64,       "ltI64")
KIELI_X_BUILTIN_DO(LtU8,        "ltU8")
KIELI_X_BUILTIN_DO(LtU16,       "ltU16")
KIELI_X_BUILTIN_DO(LtU32,       "ltU32")
KIELI_X_BUILTIN_DO(LtU64,       "ltU64")
KIELI_X_BUILTIN_DO(LtF32,       "ltF32")
KIELI_X_BUILTIN_DO(LtF64,       "ltF64")
KIELI_X_BUILTIN_DO(LogicAnd,    "logicAnd")
KIELI_X_BUILTIN_DO(LogicOr,     "logicOr")
KIELI_X_BUILTIN_DO(LogicNot,    "logicNot")
KIELI_X_BUILTIN_DO(Abort,       "abort")
KIELI_X_BUILTIN_DO(Todo,        "todo")
KIELI_X_BUILTIN_DO(Unreachable, "unreachable")

// clang-format on
