// This file is a preprocessor function, parameterized by the KIELI_X_TOKEN_DO macro. It is invoked
// by including it between a define/undef pair. There are no include guards, because this file does
// not declare anything, and may be included multiple times in a translation unit.

// https://en.wikipedia.org/wiki/X_macro

// clang-format off

// Fields: identifier, spelling, description

KIELI_X_TOKEN_DO(Unterminated_comment, "error",      "an unterminated comment")
KIELI_X_TOKEN_DO(Unterminated_string,  "error",      "an unterminated string")
KIELI_X_TOKEN_DO(Invalid_character,    "error",      "an invalid character")
KIELI_X_TOKEN_DO(Dot,                  ".",          "a dot")
KIELI_X_TOKEN_DO(Comma,                ",",          "a comma")
KIELI_X_TOKEN_DO(Colon,                ":",          "a colon")
KIELI_X_TOKEN_DO(Semicolon,            ";",          "a semicolon")
KIELI_X_TOKEN_DO(Double_colon,         "::",         "a double colon")
KIELI_X_TOKEN_DO(Ampersand,            "&",          "an ampersand")
KIELI_X_TOKEN_DO(Asterisk,             "*",          "an asterisk")
KIELI_X_TOKEN_DO(Plus,                 "+",          "a plus sign")
KIELI_X_TOKEN_DO(Equals,               "=",          "an equal sign")
KIELI_X_TOKEN_DO(Question,             "?",          "a question mark")
KIELI_X_TOKEN_DO(Exclamation,          "!",          "an exclamation mark")
KIELI_X_TOKEN_DO(At,                   "@",          "an at sign")
KIELI_X_TOKEN_DO(Pipe,                 "|",          "a pipe")
KIELI_X_TOKEN_DO(Lambda,               "\\",         "a backslash")
KIELI_X_TOKEN_DO(Left_arrow,           "<-",         "a left arrow")
KIELI_X_TOKEN_DO(Right_arrow,          "->",         "a right arrow")
KIELI_X_TOKEN_DO(Paren_open,           "(",          "an opening parenthesis")
KIELI_X_TOKEN_DO(Paren_close,          ")",          "a closing parenthesis")
KIELI_X_TOKEN_DO(Brace_open,           "{",          "an opening brace")
KIELI_X_TOKEN_DO(Brace_close,          "}",          "a closing brace")
KIELI_X_TOKEN_DO(Bracket_open,         "[",          "an opening bracket")
KIELI_X_TOKEN_DO(Bracket_close,        "]",          "a closing bracket")
KIELI_X_TOKEN_DO(Let,                  "let",        "keyword 'let'")
KIELI_X_TOKEN_DO(Mut,                  "mut",        "keyword 'mut'")
KIELI_X_TOKEN_DO(Immut,                "immut",      "keyword 'immut'")
KIELI_X_TOKEN_DO(If,                   "if",         "keyword 'if'")
KIELI_X_TOKEN_DO(Else,                 "else",       "keyword 'else'")
KIELI_X_TOKEN_DO(For,                  "for",        "keyword 'for'")
KIELI_X_TOKEN_DO(In,                   "in",         "keyword 'in'")
KIELI_X_TOKEN_DO(While,                "while",      "keyword 'while'")
KIELI_X_TOKEN_DO(Loop,                 "loop",       "keyword 'loop'")
KIELI_X_TOKEN_DO(Continue,             "continue",   "keyword 'continue'")
KIELI_X_TOKEN_DO(Break,                "break",      "keyword 'break'")
KIELI_X_TOKEN_DO(Match,                "match",      "keyword 'match'")
KIELI_X_TOKEN_DO(Ret,                  "ret",        "keyword 'ret'")
KIELI_X_TOKEN_DO(Fn,                   "fn",         "keyword 'fn'")
KIELI_X_TOKEN_DO(Enum,                 "enum",       "keyword 'enum'")
KIELI_X_TOKEN_DO(Struct,               "struct",     "keyword 'struct'")
KIELI_X_TOKEN_DO(Concept,              "concept",    "keyword 'concept'")
KIELI_X_TOKEN_DO(Impl,                 "impl",       "keyword 'impl'")
KIELI_X_TOKEN_DO(Alias,                "alias",      "keyword 'alias'")
KIELI_X_TOKEN_DO(Import,               "import",     "keyword 'import'")
KIELI_X_TOKEN_DO(Export,               "export",     "keyword 'export'")
KIELI_X_TOKEN_DO(Module,               "module",     "keyword 'module'")
KIELI_X_TOKEN_DO(Sizeof,               "sizeof",     "keyword 'sizeof'")
KIELI_X_TOKEN_DO(Typeof,               "typeof",     "keyword 'typeof'")
KIELI_X_TOKEN_DO(Where,                "where",      "keyword 'where'")
KIELI_X_TOKEN_DO(Dyn,                  "dyn",        "keyword 'dyn'")
KIELI_X_TOKEN_DO(Macro,                "macro",      "keyword 'macro'")
KIELI_X_TOKEN_DO(Defer,                "defer",      "keyword 'defer'")
KIELI_X_TOKEN_DO(Underscore,           "_",          "an underscore")
KIELI_X_TOKEN_DO(Lower_name,           "lower",      "an uncapitalized identifier")
KIELI_X_TOKEN_DO(Upper_name,           "upper",      "a capitalized identifier")
KIELI_X_TOKEN_DO(Operator,             "op",         "an operator")
KIELI_X_TOKEN_DO(Integer,              "int",        "an integer literal")
KIELI_X_TOKEN_DO(Floating,             "float",      "a floating point literal")
KIELI_X_TOKEN_DO(String,               "str",        "a string literal")
KIELI_X_TOKEN_DO(Boolean,              "bool",       "a boolean literal")
KIELI_X_TOKEN_DO(End_of_input,         "eof",        "the end of input")

// clang-format on
